version: "3.5"
services:
  artalk:
    container_name: artalk
    image: artalk/artalk
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:23366
    volumes:
      - ./data:/data
