# https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: NPM Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'ArtalkJS/Artalk'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set node version to 12.x
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Publish
      run: cd packages/artalk && yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # GitHub Packages
    #
    # Setup .npmrc file to publish to GitHub Packages
    # - uses: actions/setup-node@v2
    #   with:
    #     registry-url: 'https://npm.pkg.github.com'
    # # Publish to GitHub Packages
    # - run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Docs Update
  docs-update:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Checkout ArtalkDocs
        uses: actions/checkout@v2
        with:
          repository: ArtalkJS/Docs
          token: ${{ secrets.PAT }}

      - name: Update CDN links
        run: |
          sed -i 's#artalk@.[^/]*#artalk@${{ steps.get_version.outputs.VERSION }}#g' docs/code/ArtalkCDN.json
          sed -i 's#artalk@.[^/]*#artalk@${{ steps.get_version.outputs.VERSION }}#g' docs/code/quick-start/cdn.html

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Artalk CDN link to v${{ steps.get_version.outputs.VERSION }}
